require 'bebox/version'
require 'bebox/wizard/project_wizard'
require 'bebox/wizard/environment_wizard'
require 'bebox/wizard/node_wizard'
require 'bebox/wizard/puppet_wizard'
require 'bebox/wizard/role_wizard'
require 'bebox/wizard/profile_wizard'
require 'bebox/project'
require 'bebox/environment'
require 'bebox/node'
require 'bebox/puppet'
require 'bebox/profile'
require 'bebox/role'
require 'bebox/cli'
# Add requires for other files you add to your project here, so
# you just need to require this one file in your bin file
